[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern="function modulate_sound(dt)"
position = "before"
payload='''
local function gfuel_pitch()
    local pitch = 1
    for i=1, #G.jokers.cards do
        if G.jokers.cards[i].config.center.name == "wrenbind_gfuel" then
            pitch = pitch + 0.10
        end
    end
    return pitch
end
'''
match_indent=true

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "G.PITCH_MOD = (G.PITCH_MOD or 1)*(1 - dt) + dt*((not G.normal_music_speed and G.STATE == G.STATES.GAME_OVER) and 0.5 or 1)"
position = "at"
payload = '''
if G.jokers and G.jokers.cards then
    G.PITCH_MOD = (G.PITCH_MOD or 1)*(1 - dt) + dt*((G.STATE == G.STATES.GAME_OVER) and 0.5 or gfuel_pitch())
else
    G.PITCH_MOD = (G.PITCH_MOD or 1)*(1 - dt) + dt*((not G.normal_music_speed and G.STATE == G.STATES.GAME_OVER) and 0.5 or 1)
end
'''
match_indent = true
